import {setupAndoain} from "./andoain";
import {setupAndri}   from "./andri";
import {setupAthlon}  from "./athlon";
import {setupBjron}   from "./bjorn";
import {setupCecilia} from "./cecilia";
import {setupCoroto}  from "./coroto";
import {setupDawn}    from "./dawn";
import {setupDusk}    from "./dusk";
import {setupElysium} from "./elysium";
import {setupErica}   from "./erica";
import {setupEzell}   from "./ezell";
import {setupGenefe}  from "./genefe";
import {setupHav}     from "./hav";
import {setupHina}    from "./hina";
import {setupIngrid}  from "./ingrid";
import {setupIona}    from "./iona";
import {setupJaye}    from "./jaye";
import {setupJordi}   from "./jordi";
import {setupKastor}  from "./kastor";
import {setupPetra}   from "./petra";
import {setupRoberta} from "./roberta";
import {setupSasha}   from "./sasha";
import {setupSybilla} from "./sybilla";
import {setupTomasa}  from "./tomasa";
import {setupVerna}   from "./verna";
import {setupVitacia} from "./vitacia";
import {setupYuki}    from "./yuki";

export function setupC2A1()
{
    setupAndoain();
    setupAndri();
    setupAthlon();
    setupBjron();
    setupCecilia();
    setupCoroto();
    setupDawn();
    setupDusk();
    setupElysium();
    setupErica();
    setupEzell();
    setupGenefe();
    setupHav();
    setupHina();
    setupIngrid();
    setupIona();
    setupJaye();
    setupJordi();
    setupKastor();
    setupPetra();
    setupRoberta();
    setupSasha();
    setupSybilla();
    setupTomasa();
    setupVerna();
    setupVitacia();
    setupYuki();
}