import {IUniqueDOMGenerator} from "./IUniqueDOMGenerator";


/**
 * Implementation common to all {@link IUniqueDOMGenerator}s.
 */
export abstract class BaseUniqueDOMGenerator
    implements IUniqueDOMGenerator
{
    /**
     * A reference to the element generated by this object. Null if no element
     * has been generated yet. It is advisable to cache this value to avoid
     * frivolous lookups.
     */
    private get $element(): JQuery
    {
        const $matches = $(`#${this.id}`);
        return $matches.length == 0 ? null : $matches;
    }

    /**
     * @inheritDoc
     */
    public refreshRenderedElement()
    {
        const $element = this.$element;
        if ($element == null) {
            return;
        }
        this.doRefreshRenderedElement($element);
    }

    /**
     * The actual refresh logic.
     */
    protected doRefreshRenderedElement($element: JQuery)
    {}

    /**
     * @inheritDoc
     */
    public abstract generateDOMString(): string;

    /**
     * @inheritDoc
     */
    public abstract get id(): string;
}
