export enum MapVertexType
{
    Unknown,
    Village,
    Town,
    Fort,
    City,
    Metropolis,
    Industry,
    Trade,
    Military,
    Capital,
    ResearchHub,
    MiscCivilian,
    Base,
    Resource,
    WatchPost,
    MiscSafe,
    Conflict,
    Dungeon,
    // TowerDefense, (...)
    MiscEncounter,
    DeadlyEncounter,
    UnknownEmergency,
    MiscEmergency,
    MiscLegendary,
    Perpendicularity,
    Deity,
    Death,
}


export const MapVertexTypeDescriptions: Map<MapVertexType, string> =
    new Map([
        [MapVertexType.Unknown,          "???"],
        [MapVertexType.Village,          "Village"],
        [MapVertexType.Town,             "Town"],
        [MapVertexType.Fort,             "Fort"],
        [MapVertexType.City,             "City"],
        [MapVertexType.Metropolis,       "Metropolis"],
        [MapVertexType.Industry,         "Industrial Zone"],
        [MapVertexType.Trade,            "Market"],
        [MapVertexType.Military,         "Encampment"],
        [MapVertexType.Capital,          "State Capital"],
        [MapVertexType.ResearchHub,      "Research Centre"],
        [MapVertexType.MiscCivilian,     "Misc"],
        [MapVertexType.Base,             "Base"],
        [MapVertexType.Resource,         "Resource"],
        [MapVertexType.WatchPost,        "Watch Post"],
        [MapVertexType.MiscSafe,         "Misc"],
        [MapVertexType.Conflict,         "Conflict"],
        [MapVertexType.Dungeon,          "Dungeon"],
        [MapVertexType.MiscEncounter,    "Encounter"],
        [MapVertexType.DeadlyEncounter,  "Combat"],
        [MapVertexType.UnknownEmergency, "???"],
        [MapVertexType.MiscEmergency,    "Emergency"],
        [MapVertexType.MiscLegendary,    "Legendary"],
        [MapVertexType.Perpendicularity, "Perpendicularity"],
        [MapVertexType.Deity,            "Deity's Abode"],
        [MapVertexType.Death,            "Death"],
    ]);
